name: "Publish all libs"

on:
  push:
    tags:
      - '**'

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx5g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  SONATYPE_USER: '${{ secrets.SONATYPE_USER }}'
  SONATYPE_PWD: '${{ secrets.SONATYPE_PWD }}'
  OSS_USER: '${{ secrets.OSS_USER }}'
  OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
  OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
  SIGNING_KEY_NAME: '${{ secrets.SIGNING_KEY_NAME }}'
  SIGNING_KEY_ID: '${{ secrets.SIGNING_KEY_ID }}'
  SIGNING_KEY_PASSPHRASE: '${{ secrets.SIGNING_KEY_PASSPHRASE }}'
  SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'

jobs:
  check:
    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]

    outputs:
      saga-version: ${{ steps.get-saga-version.outputs.saga-version }}

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 11

      # For watchOS x86 simulator. Remove with Kotlin 1.8.
      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos-latest'
        with:
          xcode-version: '13.4.1'

      - name: build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build --scan --full-stacktrace

      - name: Upload reports
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - id: get-saga-version
        name: Get Saga version
        run: |
          ./gradlew
          echo "::set-output name=saga-version::$(head -n 1 build/semver/version.txt)"

  publish:
    needs: check
    env:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}

    runs-on: macos-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Publish alpha version
        if: |
          contains(needs.check.outputs.saga-version, 'alpha') ||
          contains(needs.check.outputs.saga-version, 'beta') ||
          contains(needs.check.outputs.saga-version, 'rc')
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --full-stacktrace --scan

      - name: Publish final version
        if: |
          !contains(needs.check.outputs.saga-version, 'alpha') &&
          !contains(needs.check.outputs.saga-version, 'beta') &&
          !contains(needs.check.outputs.saga-version, 'rc')
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository --full-stacktrace --scan

      - name: Stop Gradle daemons
        run: ./gradlew --stop
