name: update-docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB_ACTION }}

      - name: Set up Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Dokka
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: cleanDocs dokkaHtml --scan --full-stacktrace

      - name: Push docs
        run: |
          git config --global user.email "nomisRev@users.noreply.github.com"
          git config --global user.name "Simon Vergauwen"
          git add docs/.
          git commit -m "Automaticaly update docs"
